spring:
  application:
    name: studyFramework
  aop:
    auto: true #????????
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #    url: jdbc:mysql://172.16.1.251:3306/test0?useUnicode=true&characterEncoding=utf8&useSSL=false
    url: jdbc:mysql://localhost:3306/study_library?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5 #??????????10
      maximum-pool-size: 15 #?????,???10
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatabookHikariCP
      max-lifetime: 1800000 #????????,???30??.?????mysql????????
      connection-timeout: 30000 #??????(??),???30?.
      #????????????600000(10??),?????????????????????????????
      #?????? max-lifetime ? max-lifetime>0,??????0
      connection-test-query: SELECT 1 #??????
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: 172.16.1.238 # Redis?????
    database: 9 # Redis?????????0?
    password: '' # Redis?????????????
    timeout: 5000 # ??????????
    lettuce:
      pool: #????????????pool???????????????
        max-active: 8 #?????????,???????????
        max-idle: 8 #???????,????8,???????????
        max-wait: -1 #?????????????,????????????,????????,????-1,?????Duration
        min-idle: 0 #???????????,????????????
  rabbitmq:
    host: 172.16.1.238 #??localhost
    port: 5672 #??5672
    username: xydata
    password: xydata

mybatis:
#  configuration:
#    map-underscore-to-camel-case: true #????????????????????
     jdbc-type-for-null: 'NULL'
#  mapper-locations: classpath:mybatis/mapper/*.xml #resource?java?mapper?????????

server:
  port: 8089

logging:
  level:
    org.springframework.boot.autoconfigure: ERROR
    com.shujuan: debug #trace
  config: C:\Users\guany\IdeaProjects\studyFramework\src\main\resources\logback.xml

#mapper:
#  identity: MYSQL
#  before: true
#  u-u-i-d: true

#security:
#  oauth2:
#    client:
#      client-id: futureApplicationStore
#      client-secret: test
#      user-authorization-uri: https://172.16.1.238:8443/oauth/authorize
#      access-token-uri: https://172.16.1.238:8443/oauth/token
#      requestUrl: { 172.16.1.238: futureApplicationStore }
#      scope: all
#      registered-redirect-uri: https://172.16.1.238:7045/code
#      access-token-real-uri: https://172.16.1.238:8443/oauth/token
#    resource:
#      token-info-uri: https://172.16.1.238:8443/oauth/check_token
#      user-info-uri: https://172.16.1.238:8443/user
#      jwt:
#        #????client
#        key-uri: https://172.16.1.238:8443/oauth/token_key
#        key-value: xydata
#  interface:
#    encrypt: true
#    public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCGXsxHtxVl/rcvs4ezSOlfAOswLv1vlx6TQxyR3DOaQ2Fi0C4UvtdVX3mqjzhtjqaWIFlgq5C4BrjArFzCA0HR+FOFDxsnKSKimv3k2gaYCWgbOAQLShmfe5SfYEbziUOyxyM6CAJvDujLAAWzfyUo1XTQUFFgP5tvD6CIwIZ4OwIDAQAB
#    private-key: MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAIZezEe3FWX+ty+zh7NI6V8A6zAu/W+XHpNDHJHcM5pDYWLQLhS+11VfeaqPOG2OppYgWWCrkLgGuMCsXMIDQdH4U4UPGycpIqKa/eTaBpgJaBs4BAtKGZ97lJ9gRvOJQ7LHIzoIAm8O6MsABbN/JSjVdNBQUWA/m28PoIjAhng7AgMBAAECgYBxdZZ0b8mnx/6STrukzUoRKEtu8h6ZnTb6Dc8P8qm39nFC6JogdkyJEAdB15FEIRHU7hfKItQeL77NIj1orStjkL5b4jFXPl7VQ6EIFRyliVijQWU8GenzO+qvFJsS2DsXv6lvHG5DpNIuBcv1bNxcwedYTgxQKyNEikiul0eaoQJBAMWNdjfwThM/RgkQGD/6niYe39NdOXFO3nvXJ5wdw0M2hz28SivuPk6lCy2c29GlDsYfeAkYvWUVgbyLixu5qKMCQQCuH/DEqEFeZcOlooGCjU9g5L/++gJEiLTHA9qtB5PnprYAi/9w6cTDYiqvb6o8eeLVBB5X8kf7ENwsSB+zjnOJAkB1kDbPGVHNQHVURWC5ClL9SphWt37MwGvEdQjcbhXatOOMyLW3KQOpV6ysS1HBlCGTo/ySJUfolQDtDHoPWNBTAkA+CoVoHKdF8i52uuM4WA87b+X0/LGIJ8l5y6bD1hpeBKl+omM+oRyJnVWmMrxOVgN7cL87CMma7FP2tzAMcyo5AkAWB0aEWgXl/YKCkpnv9hM2E39BDqkKEV206uhcMsX05aVlYrOSHFaaktHjdyxoKW8uES1o9DJ/JxyWriWqM715
#    topic-exchange-name: topicExchangeTest
#    receive-routing-key: topic.testService
#    send-routing-key: topic.testReceiveService
#    queue-name: TestServiceConsumer
#    server-ip: http://127.0.0.1
#    server-port: 8089
#    concurrentConsumers: 10
#    prefetchCount: 10
